// mock.ts
export const positions_1 = [
    {
        title: "前端开发实习生",
        location: "上海",
        education: "本科",
        tags: ["在校生/应届生", "国企", "互联网/电子商务"],
        company: "交银金融科技",
        companyType: "国企",
        industry: "互联网/电子商务",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_internet.png",
        salary: "面议",
    },
    {
        title: "Web前端开发实习生（上海）",
        location: "上海",
        education: "本科",
        tags: ["在校生/应届生", "民营", "通信/电信运营、增值服务"],
        company: "亚信科技(中国)",
        companyType: "民营",
        industry: "通信/电信运营、增值服务",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/home_logo_default.png",
        salary: "3-4.5千",
    },
    {
        title: "前端实习生",
        location: "上海-徐汇区",
        education: "大专",
        tags: ["在校生/应届生", "民营", "计算机软件", "150-500人"],
        company: "上海知平信息技术",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2925/2924126/2924126_120.gif?635850140098750303",
        salary: "1-2万",
    },
    {
        title: "前端开发实习生",
        location: "上海-杨浦区",
        education: "本科",
        tags: ["在校生/应届生", "国企", "150-500人", "建筑/建材/工程"],
        company: "上海城建信息科技",
        companyType: "国企",
        industry: "建筑/建材/工程",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/8/7130/7129352/1653979188305_300.jpeg?1653979241270",
        salary: "180元/天",
    },
    {
        title: "前端开发实习生",
        location: "上海-闵行区",
        education: "大专",
        tags: ["在校生/应届生", "民营", "计算机软件", "少于50人"],
        company: "从奥软件（上海）",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/7/6354/6353007/6353007_300.png?637502826605732418",
        salary: "200元/天",
    },
    {
        title: "前端实习生--生活服务",
        location: "上海",
        education: "本科",
        tags: ["无需经验", "六险一金", "团队氛围好", "晋升空间大", "用户过亿"],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8千-1.5万",
    },
    {
        title: "前端项目实习生",
        location: "上海",
        education: "无需经验",
        tags: ["已上市", "10000人以上", "互联网/电子商务"],
        company: "美团",
        companyType: "已上市",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/5/4401/4400526/4400526_300.png?637439174362178773",
        salary: "5-7千",
    },
    {
        title: "Web前端实习生",
        location: "上海-普陀区",
        education: "本科",
        tags: [
            "无需经验",
            "国企",
            "500-1000人",
            "多元化业务集团公司",
            "css",
            "html",
            "javascript",
            "ajax",
            "前端",
            "前端开发",
            "xml",
            "json",
            "uni_app",
            "跨平台框架",
        ],
        company: "上海电器科学研究所",
        companyType: "国企",
        industry: "多元化业务集团公司",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_pluralistic.png",
        salary: "100元/天",
    },
    {
        title: "前端实习生（生活服务）",
        location: "上海",
        education: "本科",
        tags: ["无需经验", "六险一金", "团队氛围好", "晋升空间大", "用户过亿"],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "5千-1万",
    },
    {
        title: "前端开发-实习生",
        location: "上海-徐汇区",
        education: "大专",
        tags: ["在校生/应届生", "央企", "做五休二"],
        company: "普天轨道交通技术（上海）",
        companyType: "国企",
        industry: "电子技术/半导体/集成电路",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/5/4772/4771215/4771215_300.png?637025205063195152",
        salary: "120元/天",
    },
    {
        title: "前端大学实习生（大三或者大四学生）",
        location: "上海-黄浦区",
        education: "本科",
        tags: ["无需经验"],
        company: "上海贝洛商务咨询",
        companyType: "民营",
        industry: "专业服务(咨询、人力资源、财会)",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/2/1299/1298076/1298076_300.png?636869600455449277",
        salary: "200元/天",
    },
];
export const positions_2 = [
    {
        title: "前端大学实习生（大三或者大四学生）",
        location: "上海-黄浦区",
        education: "本科",
        tags: ["无需经验"],
        company: "上海贝洛商务咨询",
        companyType: "民营",
        industry: "专业服务(咨询、人力资源、财会)",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/2/1299/1298076/1298076_300.png?636869600455449277",
        salary: "200元/天",
    },
    {
        title: "前端开发工程师实习生",
        location: "上海-浦东新区",
        education: "本科",
        tags: [
            "在校生/应届生",
            "5天/周·3个月",
            "css",
            "html",
            "javascript",
            "vue",
            "react",
            "文档编写",
            "mes",
            "angular",
            "web开发",
            "机器视觉",
            "落户上海",
            "公租房",
            "周五下午茶",
            "常备咖啡点心",
        ],
        company: "上海犀浦智能系统",
        companyType: "民营",
        industry: "学术/科研",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/6/5693/5692342/5692342_300.png?637643639550862406",
        salary: "120元/天",
    },
    {
        title: "前端开发实习(24届实习或者25届）",
        location: "上海-浦东新区",
        education: "本科",
        tags: ["在校生/应届生", "前端开发", "vue", "鸿蒙", "java"],
        company: "前锦网络信息技术（上海）",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_software.png",
        salary: "200元/天",
    },
    {
        title: "前端开发实习生",
        location: "上海-闵行区",
        education: "本科",
        tags: [],
        company: "上海计算机软件技术开发中心",
        companyType: "事业单位",
        industry: "计算机软件",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/4/3587/3586900/3586900_300.png?637807090464834273",
        salary: "120元/天",
    },
    {
        title: "前端开发实习生-西瓜视频",
        location: "上海",
        education: "本科",
        tags: [
            "无需经验",
            "六险一金",
            "团队氛围好",
            "晋升空间大",
            "用户过亿",
            "大牛带队",
        ],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8-9千",
    },
    {
        title: "前端实习生-广告系统",
        location: "上海",
        education: "本科",
        tags: ["无需经验", "六险一金", "团队氛围好", "晋升空间大", "用户过亿"],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8-9千",
    },
    {
        title: "前端开发实习生",
        location: "上海",
        education: "本科",
        tags: [
            "无需经验",
            "团队氛围好",
            "用户过亿",
            "大牛带队",
            "免费三餐",
            "租房补贴",
        ],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "3-5千",
    },
    {
        title: "前端开发实习生",
        location: "上海-杨浦区",
        education: "本科",
        tags: ["在校生/应届生", "5天/周·3个月"],
        company: "中州期货",
        companyType: "民营",
        industry: "金融/投资/证券",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/6/5415/5414868/487618838120932749933_300.png?1703209668649",
        salary: "100元/天",
    },
    {
        title: "前后端研发工程师（实习生）",
        location: "上海-嘉定区",
        education: "本科",
        tags: ["无需经验"],
        company: "环球车享汽车租赁",
        companyType: "国企",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/4/3966/3965751/517799391816020956878_300.png?1706523533340",
        salary: "200元/天",
    },
    {
        title: "Web前端开发实习生",
        location: "上海-长宁区",
        education: "本科",
        tags: [
            "在校生/应届生",
            "3天/周·6个月",
            "英语",
            "计算机",
            "css",
            "javascript",
            "vue",
            "html5",
            "mvc",
            "前端开发",
            "photoshop",
            "互联网",
            "ai",
            "弹性工作",
            "绩效奖金",
            "年终奖金",
            "分红",
        ],
        company: "美知睿学",
        companyType: "民营",
        industry: "教育/培训/院校",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/2/1865/1864355/1864355_300.jpg?637621157160989683",
        salary: "150元/天",
    },
];

export const positions_z_1 = [
    {
        title: "Web前端工程师",
        location: "上海",
        education: "本科",
        tags: ["上海", "在校生/应届生", "本科"],
        company: "上海建科集团",
        companyType: "国企",
        industry: "建筑/建材/工程",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_build.png",
        salary: "8-13万",
    },
    {
        title: "前端开发工程师（上海）",
        location: "上海",
        education: "本科",
        tags: [
            "计算机科学与技术",
            "软件工程",
            "计算机",
            "vue",
            "开发",
            "软件开发",
            "数学",
            "react",
            "软件工程",
            "js",
            "津贴补贴",
            "中长期激励",
        ],
        company: "华海智汇技术",
        companyType: "民营",
        industry: "通信/电信/网络设备",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_imnetwork.png",
        salary: "1-1.8万",
    },
    {
        title: "前端开发实习生",
        location: "上海",
        education: "本科",
        tags: ["在校生/应届生", "国企", "互联网/电子商务"],
        company: "交银金融科技",
        companyType: "国企",
        industry: "互联网/电子商务",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_internet.png",
        salary: "面议",
    },
    {
        title: "前端开发实习生-西瓜视频",
        location: "上海",
        education: "本科",
        tags: [
            "无需经验",
            "六险一金",
            "团队氛围好",
            "晋升空间大",
            "用户过亿",
            "大牛带队",
        ],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8-9千",
    },
    {
        title: "前端开发实习生",
        location: "上海-闵行区",
        education: "大专",
        tags: ["在校生/应届生", "民营", "计算机软件", "少于50人"],
        company: "从奥软件（上海）",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/7/6354/6353007/6353007_300.png?637502826605732418",
        salary: "200元/天",
    },
    {
        title: "前端实习生--生活服务",
        location: "上海",
        education: "本科",
        tags: ["无需经验", "六险一金", "团队氛围好", "晋升空间大", "用户过亿"],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8千-1.5万",
    },
    {
        title: "前端项目实习生",
        location: "上海",
        education: "无需经验",
        tags: ["已上市", "10000人以上", "互联网/电子商务"],
        company: "美团",
        companyType: "已上市",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/5/4401/4400526/4400526_300.png?637439174362178773",
        salary: "5-7千",
    },
    {
        title: "前端开发工程师（校招）",
        location: "上海",
        education: "本科",
        tags: ["在校生/应届生"],
        company: "交银金融科技",
        companyType: "国企",
        industry: "互联网/电子商务",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_internet.png",
        salary: "1.5-1.9万",
    },
    {
        title: "前端开发工程师",
        location: "上海-浦东新区",
        education: "本科",
        tags: ["在校生/应届生"],
        company: "上海清鹤科技",
        companyType: "已上市",
        industry: "仪器仪表/工业自动化",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_instrumentation.png",
        salary: "1.2-2.4万",
    },
    {
        title: "前端开发工程师",
        location: "上海-浦东新区",
        education: "本科",
        tags: ["在校生/应届生"],
        company: "前锦网络信息技术（上海）",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_software.png",
        salary: "1-2万",
    },
];

export const positions_z_2 = [
    {
        title: "前端实习生-广告系统",
        location: "上海",
        education: "本科",
        tags: ["无需经验", "六险一金", "团队氛围好", "晋升空间大", "用户过亿"],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "8-9千",
    },
    {
        title: "前端开发实习生",
        location: "上海",
        education: "本科",
        tags: [
            "无需经验",
            "团队氛围好",
            "用户过亿",
            "大牛带队",
            "免费三餐",
            "租房补贴",
        ],
        company: "字节跳动",
        companyType: "民营",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/3/2759/2758227/369597024407452791094_300.png?1691407082649",
        salary: "3-5千",
    },
    {
        title: "前端开发实习生",
        location: "上海-杨浦区",
        education: "本科",
        tags: ["在校生/应届生", "5天/周·3个月"],
        company: "中州期货",
        companyType: "民营",
        industry: "金融/投资/证券",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/6/5415/5414868/487618838120932749933_300.png?1703209668649",
        salary: "100元/天",
    },
    {
        title: "前后端研发工程师（实习生）",
        location: "上海-嘉定区",
        education: "本科",
        tags: ["无需经验"],
        company: "环球车享汽车租赁",
        companyType: "国企",
        industry: "互联网/电子商务",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/4/3966/3965751/517799391816020956878_300.png?1706523533340",
        salary: "200元/天",
    },
    {
        title: "Web前端开发实习生",
        location: "上海-长宁区",
        education: "本科",
        tags: [
            "在校生/应届生",
            "3天/周·6个月",
            "英语",
            "计算机",
            "css",
            "javascript",
            "vue",
            "html5",
            "mvc",
            "前端开发",
            "photoshop",
            "互联网",
            "ai",
            "弹性工作",
            "绩效奖金",
            "年终奖金",
            "分红",
        ],
        company: "美知睿学",
        companyType: "民营",
        industry: "教育/培训/院校",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/2/1865/1864355/1864355_300.jpg?637621157160989683",
        salary: "150元/天",
    },
    {
        title: "小程序开发工程师",
        location: "上海-徐汇区",
        education: "大专",
        tags: ["1年", "小程序开发", "团建活动"],
        company: "上海统才企业管理咨询服务",
        companyType: "民营",
        industry: "专业服务(咨询、人力资源、财会)",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/7/6678/6677021/362360816562461739959_300.png?1690683416986",
        salary: "1.2-1.9万",
    },
    {
        title: "前端开发工程师",
        location: "上海-杨浦区",
        education: "本科",
        tags: ["1年及以上", "英语"],
        company: "上海复瞰科技",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_software.png",
        salary: "1-1.5万·13薪",
    },
    {
        title: "Web前端开发（小程序方向）",
        location: "上海-徐汇区",
        education: "本科",
        tags: ["无需经验"],
        company: "上海知到知识数字科技",
        companyType: "民营",
        industry: "计算机服务(系统、数据服务、维修)",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_compuserve.png",
        salary: "2-3万·13薪",
    },
    {
        title: "前端开发工程师",
        location: "上海-浦东新区",
        education: "本科",
        tags: ["1年", "国企", "150-500人", "金融/投资/证券"],
        company: "交银金融科技",
        companyType: "国企",
        industry: "金融/投资/证券",
        imgSrc: "https://img01.51jobcdn.com/fansImg/CompLogo/7/6422/6421029/227418248766607331832_300.png?1677485965041",
        salary: "1.5-3万·18薪",
    },
    {
        title: "前端开发工程师",
        location: "上海-浦东新区",
        education: "本科",
        tags: ["1年", "软件工程", "计算机科学与技术", "英语"],
        company: "上海佳依佳信息科技",
        companyType: "民营",
        industry: "计算机软件",
        imgSrc: "https://img04.51jobcdn.com/im/mkt/app/51job_phone/app/homelogo/new/home_logo_default_software.png",
        salary: "1-1.8万",
    },
];
