/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdCarousel: typeof import('./src/components/AdCarousel/index.vue')['default']
    CityBar: typeof import('./src/components/CityBar/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExpectJob: typeof import('./src/components/ExpectJob/index.vue')['default']
    FeaturedJobs: typeof import('./src/components/FeaturedJobs/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    HeadNav: typeof import('./src/components/HeadNav/index.vue')['default']
    HotEnterPriseList: typeof import('./src/components/HotEnterPriseList/index.vue')['default']
    HotEnterprisePositions: typeof import('./src/components/HotEnterprisePositions/index.vue')['default']
    HotPositionsTags: typeof import('./src/components/HotPositionsTags/index.vue')['default']
    Index2: typeof import('./src/components/Message-warp/index2.vue')['default']
    IndustryNav: typeof import('./src/components/IndustryNav/index.vue')['default']
    JobAddress: typeof import('./src/components/JobAddress/index.vue')['default']
    JobArea: typeof import('./src/components/JobArea/index.vue')['default']
    JobInfo: typeof import('./src/components/JobInfo/index.vue')['default']
    JobTitle: typeof import('./src/components/JobTitle/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog/index.vue')['default']
    MessageWarp: typeof import('./src/components/Message-warp/index.vue')['default']
    OtherFilters: typeof import('./src/components/OtherFilters/index.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeTips: typeof import('./src/components/SafeTips/index.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm/index.vue')['default']
    SearchList: typeof import('./src/components/SearchList/index.vue')['default']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
    WorkPlaceDialog: typeof import('./src/components/WorkPlaceDialog/index.vue')['default']
  }
}
